import { test,expect } from '@playwright/test';
import * as XLSX from 'xlsx';
import fs from 'node:fs/promises';
import Papa from 'papaparse';
import { readFileSync } from 'node:fs';
const oracle = JSON.parse(readFileSync(new URL('../reference/oracle.json',import.meta.url),'utf8'));
const csvFile=(text:string,name='data.csv')=>({name,mimeType:'text/plain',buffer:Buffer.from(text)});
const data='sample,x,y,group,size,z\na,1.2,2.3,A,1.0,3.2\nb,2.4,3.5,B,2.0,4.1\nc,3.6,4.7,A,3.0,6.2';
async function upload(page:any,text=data){await page.getByLabel('Import files').setInputFiles(csvFile(text));await expect(page.getByTestId('active-count')).toHaveText(String(text.trim().split('\n').length-1));}
async function scatter(page:any,text=data){await page.goto('./');await upload(page,text);await page.getByLabel('X',{exact:true}).selectOption({label:'x'});await page.getByLabel('Y',{exact:true}).selectOption({label:'y'});await expect.poll(()=>page.getByTestId('chart').evaluate((e:any)=>e.data?.[0]?.x?.length)).toBe(text.trim().split('\n').length-1);}
async function traces(page:any){return page.getByTestId('chart').evaluate((e:any)=>({data:e.data,layout:e.layout}));}
async function downloaded(page:any,button:string){const p=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const d=await p;return {name:d.suggestedFilename(),text:await fs.readFile((await d.path())!,'utf8')};}
async function analysis(page:any,text:string){await page.goto('./');await page.getByRole('button',{name:'PCA/LDA',exact:true}).click();await upload(page,text);await expect(page.getByText(/analyzed rows ·/)).toBeVisible({timeout:150000});}
function closeEnough(a:number,b:number){expect(Math.abs(a-b)).toBeLessThanOrEqual(1e-8+1e-7*Math.abs(b));}

test('legacy startup, worksheet preservation, clear and per-tool session release',async({page})=>{
 await page.goto('./');await expect(page.getByRole('heading',{name:'Scatter plots'})).toBeVisible();
 const book=XLSX.utils.book_new();for(const name of ['One','Two'])XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['label','x','y'],['a',1.2,2.4],['b',3.4,4.6]]),name);
 await page.getByLabel('Import files').setInputFiles({name:'sheets.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});await expect(page.getByTestId('active-count')).toHaveText('2');
 await expect(page.getByLabel('Import files')).toBeDisabled();await page.getByLabel('X',{exact:true}).selectOption({label:'x'});await page.getByLabel('Y',{exact:true}).selectOption({label:'y'});await page.getByLabel('Active dataset').selectOption('1');await expect(page.getByLabel('X',{exact:true})).toHaveValue('c1');await expect(page.getByLabel('Y',{exact:true})).toHaveValue('c2');
 await page.getByRole('button',{name:'Clear Data',exact:true}).click();await expect(page.getByLabel('Import files')).toBeEnabled();await upload(page);await page.getByRole('button',{name:'Lines',exact:true}).click();await expect(page.getByTestId('active-count')).toHaveCount(0);await page.getByRole('button',{name:'Scatter',exact:true}).click();await expect(page.getByTestId('active-count')).toHaveCount(0);
});
test('all import formats, mixed batch, duplicate names, invalid and capacity boundaries',async({page})=>{
 await page.goto('./');
 for(const [ext,text] of [['csv','label,x,y\na,1,2\nb,3,4'],['tsv','label\tx\ty\na\t1\t2\nb\t3\t4'],['txt','label x y\na 1 2\nb 3 4'],['dat','label;x;y\na;1;2\nb;3;4']]){await page.getByLabel('Import files').setInputFiles(csvFile(text,`data.${ext}`));await expect(page.getByTestId('active-count')).toHaveText('2');await page.getByRole('button',{name:'Clear Data'}).click();}
 for(const [extension,bookType] of [['xlsx','xlsx'],['xls','biff8'],['ods','ods']] as const){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['label','x','y'],['a',1,2],['b',3,4]]),'One');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['label','x'],['c',5]]),'Two');await page.getByLabel('Import files').setInputFiles({name:`book.${extension}`,mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType})});await expect(page.getByTestId('active-count')).toHaveText('2');await page.getByLabel('Active dataset').selectOption('1');await expect(page.getByTestId('active-count')).toHaveText('1');await page.getByRole('button',{name:'Clear Data'}).click();}
 await page.getByLabel('Import files').setInputFiles([csvFile('a,a\n1,2','a.csv'),csvFile('x\ty\n3\t4','b.tsv')]);await expect(page.getByRole('status')).toContainText('Duplicate');await expect(page.getByLabel('Active dataset').locator('option')).toHaveCount(2);await page.getByRole('button',{name:'Clear Data'}).click();
 await page.getByLabel('Import files').setInputFiles(csvFile(''));await expect(page.getByRole('alert')).toContainText('empty');await page.getByLabel('Import files').setInputFiles({name:'big.csv',mimeType:'text/csv',buffer:Buffer.alloc(20*1024*1024+1)});await expect(page.getByRole('alert')).toContainText('20 MB');
 await page.getByLabel('Import files').setInputFiles(csvFile('x\n'+'1\n'.repeat(100001)));await expect(page.getByRole('alert')).toContainText('row limit');
 const wide=Array.from({length:13},(_,i)=>`c${i}`).join(',')+'\n'+('1,'.repeat(12)+'1\n').repeat(40000);await page.getByLabel('Import files').setInputFiles([csvFile(wide,'a.csv'),csvFile(wide,'b.csv')]);await expect(page.getByRole('alert')).toContainText('1,000,000');await expect(page.getByTestId('active-count')).toHaveCount(0);
});
test('50-row popup, sorting, cross-page selection and filtered CSV keep stable row IDs',async({page})=>{
 const text='sample,x,y,group\n'+Array.from({length:120},(_,i)=>`row-${i+1},${i+0.1},${i+1.2},${i<60?'A':'B'}`).join('\n');await scatter(page,text);await page.getByLabel('Color',{exact:true}).selectOption({label:'group'});await page.getByRole('button',{name:'View Data'}).click();await expect(page.getByRole('dialog').getByText('Page 1 of 3')).toBeVisible();await page.getByRole('checkbox',{name:'Select row 1',exact:true}).check();await page.getByRole('button',{name:'Next page'}).click();await page.getByRole('checkbox',{name:'Select row 51',exact:true}).check();await page.getByRole('button',{name:'Previous page'}).click();await expect(page.getByRole('checkbox',{name:'Select row 1',exact:true})).toBeChecked();await expect(page.getByTestId('active-count')).toHaveText('2');
 await page.getByLabel('Filter group',{exact:true}).fill('= B');await expect(page.getByTestId('matching-count')).toHaveText('60');await expect(page.getByTestId('active-count')).toHaveText('0');await page.getByRole('button',{name:'Close data'}).click();await expect.poll(async()=> (await traces(page)).data?.length).toBe(0);
 await page.getByRole('button',{name:'Clear selection'}).click();await expect(page.getByTestId('active-count')).toHaveText('60');const d=await downloaded(page,'Download CSV');const records=Papa.parse(d.text,{header:true,skipEmptyLines:true}).data as any[];expect(records).toHaveLength(60);expect(records.every(r=>r.group==='B')).toBe(true);expect(Object.keys(records[0])).toEqual(['sample','x','y','group']);
 await page.getByRole('button',{name:'View Data'}).click();await page.getByRole('button',{name:'x',exact:true}).click();await page.getByRole('button',{name:'x ↑',exact:true}).click();await expect(page.getByRole('dialog').locator('tbody tr').first()).toContainText('row-120');
});
test('real mouse click annotates; legend, zoom, reset and editable SVG toolbar work',async({page})=>{
 await scatter(page);await page.getByLabel('Color',{exact:true}).selectOption({label:'group'});await expect(page.locator('.scatterlayer .point')).toHaveCount(3);await page.locator('.scatterlayer .point').first().click({force:true});await expect.poll(async()=> (await traces(page)).layout.annotations.length).toBe(1);await expect(page.getByTestId('active-count')).toHaveText('3');
 await page.locator('.legend .legendtoggle').first().click();await expect.poll(async()=> (await traces(page)).data[0].visible).toBe('legendonly');await page.locator('.legend .legendtoggle').first().click();await expect.poll(async()=> (await traces(page)).data[0].visible).toBe(true);
 const box=await page.locator('.nsewdrag').boundingBox();if(!box)throw Error('No zoom area');await page.mouse.move(box.x+box.width*.15,box.y+box.height*.2);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.8,{steps:10});await page.mouse.up();await expect.poll(async()=> (await traces(page)).layout.xaxis.autorange).toBe(false);await page.locator('.nsewdrag').dblclick({force:true,position:{x:30,y:30}});await expect.poll(async()=> (await traces(page)).layout.xaxis.autorange).toBe(true);
 expect(await page.getByTestId('chart').evaluate((e:any)=>e._context.editable)).toBe(true);const d=page.waitForEvent('download');await page.getByTestId('chart').hover();await page.locator('[data-title*="Download plot"]').click();expect((await d).suggestedFilename()).toMatch(/\.svg$/);
});
test('automatic histogram / box, continuous Jet colors, sizes, log, 3D and images',async({page},info)=>{
 await scatter(page);await page.getByLabel('Y',{exact:true}).selectOption('');await expect.poll(async()=> (await traces(page)).data[0].type).toBe('histogram');await page.getByLabel('X',{exact:true}).selectOption({label:'group'});await page.getByLabel('Y',{exact:true}).selectOption({label:'y'});await expect.poll(async()=> (await traces(page)).data[0].type).toBe('box');expect((await traces(page)).data[0].boxpoints).toBe('all');
 await page.getByLabel('X',{exact:true}).selectOption({label:'x'});await page.getByLabel('Color',{exact:true}).selectOption({label:'y'});await page.getByLabel('Size',{exact:true}).selectOption({label:'size'});await page.getByRole('group',{name:'X scale'}).getByRole('radio',{name:'Log',exact:true}).check();await expect.poll(async()=> (await traces(page)).layout.xaxis.type).toBe('log');const m=await traces(page);expect(m.data[0].marker.colorscale).toBe('Jet');expect(m.data[0].marker.size).toEqual([10,25,40]);expect(m.layout.font).toEqual({family:'Arial',size:18});
 if(info.project.name==='chromium'){await page.getByRole('radio',{name:'3D',exact:true}).check();await page.getByLabel('Z',{exact:true}).selectOption({label:'z'});await expect(page.locator('.gl-container canvas').first()).toBeVisible();await expect.poll(async()=> (await traces(page)).data[0].type).toBe('scatter3d');}
 expect((await downloaded(page,'Download SVG')).text).toContain('<svg');await page.getByText('Advanced',{exact:true}).click();const p=page.waitForEvent('download');await page.getByRole('button',{name:'Download PNG'}).click();expect((await p).suggestedFilename()).toMatch(/\.png$/);await expect(page.locator('.plot-error')).toHaveCount(0);
});
test('both line formats preserve original row order and multi-Y choices',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'Lines',exact:true}).click();await upload(page,'x1,y1,x2,y2\n3.0,1.5,4.0,2.1\n1.0,2.5,6.0,5.2\n2.0,3.5,5.0,3.2');await page.getByLabel('Y columns').selectOption(['c1','c3']);await expect.poll(async()=> (await traces(page)).data?.length).toBe(2);expect((await traces(page)).data[0].x).toEqual([3,1,2]);expect((await traces(page)).data[1].x).toEqual([3,1,2]);
 await page.getByRole('radio',{name:'Type 2'}).check();await page.getByLabel('Y columns').selectOption(['c1','c3']);await expect.poll(async()=> (await traces(page)).data[1]?.x).toEqual([4,6,5]);await page.getByRole('button',{name:'View Data'}).click();await expect(page.getByRole('dialog').locator('input')).toHaveCount(0);await page.getByRole('button',{name:'Close data'}).click();expect((await downloaded(page,'Download CSV')).text.split(/\r?\n/)[0].replace(/^\uFEFF/,'')).toBe('x1,y1,x2,y2');
});
test('public oxygen replay/static, Wine defaults, historical stocks date controls',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'Static oxygen adsorption',exact:true}).click();await expect(page.getByTestId('active-count')).toHaveText('2,932');await expect(page.getByLabel('Active dataset')).toHaveValue('7');await expect(page.getByLabel('X',{exact:true})).toHaveValue('c1');await page.getByRole('button',{name:'Examples',exact:true}).click();await page.getByRole('button',{name:/Dynamic oxygen adsorption/}).click();await expect(page.getByTestId('active-count')).toHaveText('150');await expect(page.getByTestId('active-count')).toHaveText('300',{timeout:10000});await page.getByRole('button',{name:'Pause replay'}).click();
 await page.getByRole('button',{name:'Examples',exact:true}).click();await page.getByRole('button',{name:/Wine data histograms/}).click();await expect(page.getByTestId('active-count')).toHaveText('178');await expect.poll(async()=> (await traces(page)).data[0].type).toBe('box');await expect(page.getByLabel('X',{exact:true})).toHaveValue('c1');
 await page.getByRole('button',{name:'Examples',exact:true}).click();await page.getByRole('button',{name:/Stock market lines/}).click();await expect.poll(async()=> (await traces(page)).data?.length).toBe(4);await page.getByLabel('Start year').fill('2023');await expect.poll(async()=> (await traces(page)).data[0].x.every((s:string)=>s.startsWith('2023'))).toBe(true);await page.getByLabel('Y columns').selectOption({label:'Close'});await expect.poll(async()=> (await traces(page)).data?.length).toBe(1);
});
test('lazy scientific load fails cleanly; cancel suppresses automatic restart and retry succeeds',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'PCA/LDA',exact:true}).click();await page.route('https://cdn.jsdelivr.net/pyodide/**',route=>route.abort());await upload(page,'sample,x,y\na,1.2,2.3\nb,2.4,3.1\nc,3.6,4.2');await expect(page.getByRole('alert')).toContainText('Analysis failed');await page.unroute('https://cdn.jsdelivr.net/pyodide/**');
 await page.route('https://cdn.jsdelivr.net/pyodide/**',async route=>{await new Promise(r=>setTimeout(r,2500));await route.continue().catch(()=>{});});await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByText('Analysis cancelled.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toHaveCount(0);await page.unroute('https://cdn.jsdelivr.net/pyodide/**');await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByText(/3 analyzed rows/)).toBeVisible({timeout:150000});await expect(page.getByTestId('variance-chart')).toBeVisible();
});
test('PCA/LDA match locked old-version scores and ratios; display directions and CSV columns',async({page})=>{
 const c=oracle.cases.pca;await analysis(page,Papa.unparse(c.table));await page.getByLabel('Classes').selectOption({label:'class'});await expect(page.getByText(/9 analyzed rows · 3 features/)).toBeVisible({timeout:150000});await expect.poll(async()=> (await traces(page)).data?.length).toBe(3);
 let csv=await downloaded(page,'Download CSV');let records=Papa.parse(csv.text,{header:true,skipEmptyLines:true}).data as any[];expect(Object.keys(records[0])).toEqual(['PC 1','PC 2','PC 3','Individual','Cumulative']);
 records.forEach((r,i)=>{c.scores[i].forEach((v,j)=>closeEnough(Number(r[`PC ${j+1}`]),v));if(i<c.variance.length){closeEnough(Number(r.Individual),c.variance[i]);closeEnough(Number(r.Cumulative),c.cumulative[i]);}});
 await page.getByRole('radio',{name:'LDA',exact:true}).check();await expect(page.getByText(/9 analyzed rows · 3 features/)).toBeVisible({timeout:150000});await expect.poll(async()=> (await traces(page)).layout.xaxis.title.text).toBe('LD 1');csv=await downloaded(page,'Download CSV');records=Papa.parse(csv.text,{header:true,skipEmptyLines:true}).data as any[];oracle.cases.lda.scores.forEach((r:number[],i:number)=>r.forEach((v,j)=>closeEnough(Number(records[i][`LD ${j+1}`]),v)));
 const trace=(await traces(page)).data[0];closeEnough(trace.x[0],-oracle.cases.lda.scores[0][0]);const variance=await page.getByTestId('variance-chart').evaluate((e:any)=>e.data[0].y);variance.forEach((v:number,i:number)=>closeEnough(v,oracle.cases.lda.variance[i]));
 await page.getByText('Advanced',{exact:true}).click();await page.getByRole('checkbox',{name:'Automatically run analysis when data or parameters change'}).uncheck();await page.getByLabel('Classes').selectOption('');await expect(page.getByText('Previous result is out of date.')).toBeVisible();await expect(page.getByRole('button',{name:'Download CSV',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByRole('alert')).toContainText('LDA requires a class label');
 await page.getByRole('radio',{name:'PCA',exact:true}).check();await page.getByRole('checkbox',{name:'Enable box / lasso subset selection and extended table selection'}).check();await page.getByRole('button',{name:'View Data'}).click();await page.getByLabel('Filter class').fill('= A');await page.getByRole('checkbox',{name:'Select row 1',exact:true}).check();await page.getByRole('checkbox',{name:'Select row 3',exact:true}).check();await expect(page.getByTestId('active-count')).toHaveText('2');await page.getByRole('button',{name:'Close data'}).click();await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByText(/2 analyzed rows/)).toBeVisible({timeout:150000});const selected=Papa.parse((await downloaded(page,'Scores with settings CSV')).text,{header:true,skipEmptyLines:true}).data as any[];expect(selected.map(r=>r.row_id)).toEqual(['0','2']);expect(selected.every(r=>r.features==='x; y; z')).toBe(true);const subset=Papa.parse((await downloaded(page,'Full-column subset CSV')).text,{header:true,skipEmptyLines:true}).data as any[];expect(subset.map(r=>r.sample)).toEqual(['a','c']);
});
test('Iris automatic defaults and single-dimension / missing / constant corrections',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'Iris classification',exact:true}).click();await expect(page.getByText(/150 analyzed rows · 4 features/)).toBeVisible({timeout:150000});await expect(page.getByLabel('Classes')).toHaveValue('');await page.getByRole('radio',{name:'LDA',exact:true}).check();await expect(page.getByLabel('Classes')).toHaveValue('c5');await expect(page.getByText(/150 analyzed rows/)).toBeVisible({timeout:150000});
 await page.getByRole('button',{name:'PCA/LDA',exact:true}).click();await upload(page,'sample,x,constant,class\na,1.0,4.0,A\nb,2.0,4.0,A\nc,3.0,4.0,B\nd,,4.0,B');await expect(page.getByText(/3 analyzed rows · 1 features · 1 incomplete rows excluded · Constant features excluded: constant/)).toBeVisible({timeout:150000});await expect.poll(async()=> (await traces(page)).data[0].y).toEqual([0,0,0]);await page.getByRole('radio',{name:'LDA',exact:true}).check();await page.getByLabel('Classes').selectOption({label:'class'});await expect(page.getByText(/analyzed rows ·/)).toBeVisible({timeout:150000});await page.getByRole('button',{name:'View Data'}).click();await page.getByLabel('Filter class').fill('= A');await expect(page.getByRole('alert')).toContainText('at least two classes');await page.getByRole('button',{name:'Close data'}).click();
});
test('switch / clear during cold start invalidates jobs; integers stay in Advanced',async({page})=>{
 await page.goto('./');await page.getByRole('button',{name:'PCA/LDA',exact:true}).click();await upload(page,'sample,x,y\na,1,2\nb,2,1\nc,3,3');await expect(page.getByRole('alert')).toContainText('No floating-point features');await page.getByText('Advanced',{exact:true}).click();await page.getByRole('checkbox',{name:'Include integer features / choose features'}).check();await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeVisible();await page.getByRole('button',{name:'Clear Data'}).click();await expect(page.getByLabel('Import files')).toBeEnabled();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toHaveCount(0);await upload(page,'sample,x,y\na,1.2,2.3\nb,2.4,1.2\nc,3.6,4.5');await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeVisible();await page.getByRole('button',{name:'Scatter',exact:true}).click();await expect(page.getByTestId('active-count')).toHaveCount(0);
});
test('mobile, clear-on-refresh and no dataset payloads / persistent storage',async({page})=>{
 await page.setViewportSize({width:390,height:844});const requests:string[]=[];page.on('request',r=>requests.push(r.url()+(r.postData()??'')));await page.goto('./');await upload(page,'sample,x,y\nUNIQUE_PRIVATE_SENTINEL_9724,1.2,2.3\na,3.4,4.5');expect(requests.some(r=>r.includes('UNIQUE_PRIVATE_SENTINEL_9724'))).toBe(false);expect(await page.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)}))).toEqual({local:[],session:[]});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.reload();await expect(page.getByTestId('active-count')).toHaveCount(0);
});
